/*ALTER TABLE acervo ADD COLUMN id_autor INTEGER;
ALTER TABLE acervo ADD COLUMN id_editora INTEGER;*/

/*ALTER TABLE acervo
ADD CONSTRAINT fk_acervo_autor
FOREIGN KEY (id_autor) REFERENCES autor(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE acervo
ADD CONSTRAINT fk_acervo_editora
FOREIGN KEY (id_editora) REFERENCES editora(id) ON DELETE CASCADE ON UPDATE CASCADE;*/
